name: Publish Gem

on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Build gem
        run: |
          gem build jekyll-generate-favicons.gemspec --output jekyll-generate-favicons.gem
      - name: Publish
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_PUBLISH_SECRET }}
        run: |
          gem push jekyll-generate-favicons.gem
